// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4FbEQSCd5XOzOuBSLAgbXURCjrrUjmek',
    appId: '1:796790368349:web:733b68b88744ee5b6045b4',
    messagingSenderId: '796790368349',
    projectId: 'petiborn-8a9f9',
    authDomain: 'petiborn-8a9f9.firebaseapp.com',
    storageBucket: 'petiborn-8a9f9.appspot.com',
    measurementId: 'G-JWXE2ETHDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8uSruswd0TrxPVA-oz4M9mItFDBbCnpc',
    appId: '1:796790368349:android:c0d223572ee8737c6045b4',
    messagingSenderId: '796790368349',
    projectId: 'petiborn-8a9f9',
    storageBucket: 'petiborn-8a9f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnOWFjobeGHZld2Pry_5NzmIbvGnCEKPE',
    appId: '1:796790368349:ios:c0a69c26752f2fd46045b4',
    messagingSenderId: '796790368349',
    projectId: 'petiborn-8a9f9',
    storageBucket: 'petiborn-8a9f9.appspot.com',
    iosBundleId: 'com.example.petiborn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnOWFjobeGHZld2Pry_5NzmIbvGnCEKPE',
    appId: '1:796790368349:ios:c0a69c26752f2fd46045b4',
    messagingSenderId: '796790368349',
    projectId: 'petiborn-8a9f9',
    storageBucket: 'petiborn-8a9f9.appspot.com',
    iosBundleId: 'com.example.petiborn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4FbEQSCd5XOzOuBSLAgbXURCjrrUjmek',
    appId: '1:796790368349:web:efe7e8172789baa86045b4',
    messagingSenderId: '796790368349',
    projectId: 'petiborn-8a9f9',
    authDomain: 'petiborn-8a9f9.firebaseapp.com',
    storageBucket: 'petiborn-8a9f9.appspot.com',
    measurementId: 'G-NJDC3PQ4T5',
  );
}
